### ISSUE TITLE
Logging doesn't work in 1.4 the way documentation mentions

### ISSUE THREAD

**Issue by spunkedy** [larskrantz/logger_papertrail_backend#10]
I am running Elixir 1.4.2

This works

``` 
def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [extra_applications: [:logger,:logger_papertrail_backend],
     applications: [:quantum]]
  end
```

This does not

```
def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [extra_applications: [:logger],
     applications: [:quantum]]
  end
```

Which the README mentions that it should. Am I mis interpreting something?

**Comment by larskrantz** [comment]
Hi @spunkedy - There is a test application at https://github.com/larskrantz/logger_papertrail_test - please test that one to see if it works for you!
I can reproduce your problem if I specify `applications` too. I think the problem is that you specify both `extra_applications` and `applications` in your `mix.exs` - I think you must use one or the other, not both. If you specify `applications` at all, it overrides the inferred applications taken from `deps()`.
